/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kotlinmain;

public class App {

    public static void main(String[] args) {
        KotlinAppKt.kotlinMain();
        JavaApp.javaMain();
    }
}
